language: python
sudo: false

python:
  - 2.7

install:
    - pip install https://github.com/cloudify-cosmo/cloudify-rest-client/archive/3.2m8.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/3.2m8.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/3.2m8.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.2m8.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/3.2m8.zip
    - pip install flake8

env:
    - OP="validate-blueprints"

script:
    - |
        set -e
        if [ "${OP}" == "validate-blueprints" ]; then
          cfy init
          cfy blueprints validate -p aws-ec2-blueprint.yaml
          cfy blueprints validate -p openstack-blueprint.yaml
          cfy blueprints validate -p simple-blueprint.yaml
        else
          exit 1
        fi;
